version: 2

dependencies:
  override:
    - yarn

test:
  override:
    - yarn test

jobs:

  build-test:

    docker:
      - image: circleci/php:7.2-node-browsers

    working_directory: ~/laravel

    steps:

      - checkout

      - run: sudo apt-get install -y libsqlite3-dev zlib1g-dev default-mysql-client libpng-dev libjpeg62-turbo-dev libfreetype6-dev
      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - run: sudo docker-php-ext-install zip pdo_mysql gd exif
      - run: sudo composer self-update
      - run: cp .env.circleci .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: php artisan key:generate
      - run: ./vendor/bin/phpunit
      - run: composer cs

  deploy-prod:

    docker:
      - image: circleci/php:7.2-node-browsers

    working_directory: ~/laravel

    steps:
      - add_ssh_keys:
          fingerprints:
            - "b2:5f:f2:7c:e9:f7:dd:88:d4:84:db:27:e5:fa:5d:52"
      - run:
          name: install open ssl
          command: sudo apt-get install openssh-server
      - run:
          name: Test existance of .ssh directory
          command: mkdir -p "/home/circleci/.ssh"
      - run:
          name: Deploy if tests pass and branch is Master
          command: ssh -o StrictHostKeyChecking=no currency@34.253.173.230 "./deploy"


workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - master
                - develop
      - deploy-prod:
          requires:
            - build-test
          filters:
            branches:
              only: master
